name: Copilot CLI Automation
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  copilot-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6 
        with:
          node-version: 22

      - name: Install Copilot CLI  
        run: npm i -g @github/copilot

      - name: Run Copilot Command
        env:
          COPILOT_GITHUB_TOKEN: ${{ secrets.COPILOT_PAT || secrets.GITHUB_TOKEN || github.token }}
        run: |
          copilot \
            -p "Use the review-doc-organizer agent and perform a code review and use pr-change-summary skill to provide a summary of the code for human review." \
            -s --no-ask-user > copilot-output.txt
        
      - name: Post Comment to PR
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          # Option 1: If your comment is saved in a text file
          gh pr comment $PR_NUMBER --body-file "copilot-output.txt"
